# Generated by Django 3.0.3 on 2020-05-04 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='last_updated',
            field=models.DateTimeField(verbose_name='last_updated'),
        ),
        migrations.AlterField(
            model_name='country',
            name='slug',
            field=models.CharField(max_length=50),
        ),
    ]
