# Generated by Django 3.0.4 on 2020-04-25 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(verbose_name='time')),
                ('country', models.CharField(max_length=50)),
                ('country_code', models.CharField(max_length=2)),
                ('confirmed', models.IntegerField(verbose_name='confirmed')),
                ('recovered', models.IntegerField(verbose_name='recovered')),
                ('deaths', models.IntegerField(verbose_name='deaths')),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(max_length=50)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Country')),
            ],
        ),
        migrations.DeleteModel(
            name='Source',
        ),
    ]
