# Generated by Django 3.0.3 on 2020-05-03 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='date',
            name='dashboard_d_date_21fb65_idx',
        ),
        migrations.AlterField(
            model_name='country',
            name='slug',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AddIndex(
            model_name='date',
            index=models.Index(fields=['country'], name='dashboard_d_country_7d8fab_idx'),
        ),
    ]
