# Generated by Django 3.0.4 on 2020-04-25 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20200425_1336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='time',
        ),
        migrations.AddField(
            model_name='country',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='last_updated'),
        ),
        migrations.AlterField(
            model_name='country',
            name='confirmed',
            field=models.IntegerField(default=0, verbose_name='confirmed'),
        ),
        migrations.AlterField(
            model_name='country',
            name='deaths',
            field=models.IntegerField(default=0, verbose_name='deaths'),
        ),
        migrations.AlterField(
            model_name='country',
            name='recovered',
            field=models.IntegerField(default=0, verbose_name='recovered'),
        ),
    ]
