# Generated by Django 3.0.3 on 2020-05-03 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20200502_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='last_updated',
            field=models.DateTimeField(verbose_name='last_updated'),
        ),
        migrations.AlterField(
            model_name='date',
            name='date',
            field=models.DateTimeField(verbose_name='date'),
        ),
    ]
