# Generated by Django 3.0.3 on 2020-05-05 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20200504_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='slug',
            field=models.CharField(max_length=50),
        ),
    ]
