# Generated by Django 3.0.4 on 2020-04-25 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20200425_1343'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='province',
            options={'ordering': ['name']},
        ),
        migrations.RenameField(
            model_name='country',
            old_name='country_code',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='country',
            old_name='country',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='country',
            name='confirmed',
        ),
        migrations.RemoveField(
            model_name='country',
            name='deaths',
        ),
        migrations.RemoveField(
            model_name='country',
            name='last_updated',
        ),
        migrations.RemoveField(
            model_name='country',
            name='recovered',
        ),
        migrations.RemoveField(
            model_name='province',
            name='province',
        ),
        migrations.AddField(
            model_name='province',
            name='confirmed',
            field=models.IntegerField(default=0, verbose_name='confirmed'),
        ),
        migrations.AddField(
            model_name='province',
            name='deaths',
            field=models.IntegerField(default=0, verbose_name='deaths'),
        ),
        migrations.AddField(
            model_name='province',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='last_updated'),
        ),
        migrations.AddField(
            model_name='province',
            name='name',
            field=models.CharField(default='nan', max_length=50),
        ),
        migrations.AddField(
            model_name='province',
            name='recovered',
            field=models.IntegerField(default=0, verbose_name='recovered'),
        ),
    ]
