# Generated by Django 3.0.4 on 2020-04-25 21:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20200425_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='province',
            name='latitude',
            field=models.DecimalField(decimal_places=18, max_digits=20, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)]),
        ),
        migrations.AlterField(
            model_name='province',
            name='longitude',
            field=models.DecimalField(decimal_places=19, max_digits=21, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)]),
        ),
    ]
