# Generated by Django 3.0.4 on 2020-04-25 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_auto_20200425_1545'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='province',
            name='last_updated',
        ),
    ]
