# Generated by Django 3.0.4 on 2020-04-25 23:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_remove_province_last_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='province',
            name='datetime',
            field=models.TimeField(default=datetime.datetime(2020, 4, 25, 16, 2, 31, 422257), verbose_name='datetime'),
        ),
    ]
