# Generated by Django 3.0.4 on 2020-04-25 23:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_province_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='province',
            name='datetime',
            field=models.TimeField(default=datetime.datetime(2020, 4, 25, 16, 5, 35, 227373), verbose_name='datetime'),
        ),
    ]
