# Generated by Django 3.0.4 on 2020-04-26 01:02

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_auto_20200425_1605'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coordinates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=18, max_digits=20, null=True, unique=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('longitude', models.DecimalField(decimal_places=19, max_digits=21, null=True, unique=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
            ],
        ),
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmed', models.IntegerField(default=0, verbose_name='confirmed')),
                ('recovered', models.IntegerField(default=0, verbose_name='recovered')),
                ('deaths', models.IntegerField(default=0, verbose_name='deaths')),
            ],
        ),
        migrations.RemoveField(
            model_name='province',
            name='confirmed',
        ),
        migrations.RemoveField(
            model_name='province',
            name='deaths',
        ),
        migrations.RemoveField(
            model_name='province',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='province',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='province',
            name='recovered',
        ),
        migrations.AlterField(
            model_name='province',
            name='datetime',
            field=models.TimeField(default=datetime.datetime(2020, 4, 25, 18, 2, 42, 865718), verbose_name='datetime'),
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='date')),
                ('value', models.IntegerField(verbose_name='value')),
                ('category', models.CharField(choices=[('CONFIRMED', 'confirmed'), ('RECOVERED', 'recovered'), ('DEATHS', 'deaths')], max_length=10)),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Province')),
            ],
        ),
        migrations.AddField(
            model_name='province',
            name='coordinates',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Coordinates'),
        ),
        migrations.AddField(
            model_name='province',
            name='stats',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Stats'),
        ),
    ]
