# Generated by Django 3.0.4 on 2020-04-26 01:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_auto_20200425_1810'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Coordinates',
            new_name='Coordinate',
        ),
        migrations.RenameModel(
            old_name='Stats',
            new_name='Stat',
        ),
        migrations.AlterField(
            model_name='province',
            name='datetime',
            field=models.TimeField(default=datetime.datetime(2020, 4, 25, 18, 12, 12, 761235), verbose_name='datetime'),
        ),
    ]
