# Generated by Django 3.0.4 on 2020-04-26 01:29

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_auto_20200425_1817'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='province',
            name='stats',
        ),
        migrations.AddField(
            model_name='stat',
            name='province',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Province'),
        ),
        migrations.AlterField(
            model_name='country',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='province',
            name='datetime',
            field=models.TimeField(default=datetime.datetime(2020, 4, 25, 18, 29, 50, 622806), verbose_name='datetime'),
        ),
    ]
