# Generated by Django 3.0.4 on 2020-04-26 01:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_auto_20200425_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='province',
            name='datetime',
            field=models.TimeField(default=datetime.datetime(2020, 4, 25, 18, 35, 0, 723359), verbose_name='datetime'),
        ),
    ]
