# Generated by Django 3.0.4 on 2020-04-26 01:40

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_auto_20200425_1835'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='province',
            name='coordinates',
        ),
        migrations.AddField(
            model_name='coordinate',
            name='province',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Province'),
        ),
        migrations.AlterField(
            model_name='province',
            name='datetime',
            field=models.TimeField(default=datetime.datetime(2020, 4, 25, 18, 40, 13, 834824), verbose_name='datetime'),
        ),
    ]
