# Generated by Django 3.0.4 on 2020-04-26 02:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0021_auto_20200425_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='province',
            name='datetime',
            field=models.TimeField(default=datetime.datetime(2020, 4, 25, 19, 0, 37, 492584), verbose_name='datetime'),
        ),
    ]
