# Generated by Django 3.0.4 on 2020-04-26 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0022_auto_20200425_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='province',
            name='datetime',
            field=models.DateTimeField(verbose_name='datetime'),
        ),
    ]
