# Generated by Django 3.0.4 on 2020-04-26 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0024_auto_20200425_1904'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='province',
            options={},
        ),
        migrations.AlterField(
            model_name='country',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
