# Generated by Django 3.0.3 on 2020-04-26 09:13

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0025_auto_20200425_1959'),
    ]

    operations = [
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='date')),
                ('confirmed', models.IntegerField(default=0, verbose_name='confirmed')),
                ('recovered', models.IntegerField(default=0, verbose_name='recovered')),
                ('deaths', models.IntegerField(default=0, verbose_name='deaths')),
            ],
        ),
        migrations.RemoveField(
            model_name='coordinate',
            name='province',
        ),
        migrations.RemoveField(
            model_name='province',
            name='country',
        ),
        migrations.RemoveField(
            model_name='stat',
            name='province',
        ),
        migrations.AddField(
            model_name='country',
            name='confirmed',
            field=models.IntegerField(default=0, verbose_name='confirmed'),
        ),
        migrations.AddField(
            model_name='country',
            name='deaths',
            field=models.IntegerField(default=0, verbose_name='deaths'),
        ),
        migrations.AddField(
            model_name='country',
            name='last_updated',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 26, 9, 13, 11, 368534, tzinfo=utc), verbose_name='last_updated'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='country',
            name='mortality',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='mortality'),
        ),
        migrations.AddField(
            model_name='country',
            name='recovered',
            field=models.IntegerField(default=0, verbose_name='recovered'),
        ),
        migrations.DeleteModel(
            name='Case',
        ),
        migrations.DeleteModel(
            name='Coordinate',
        ),
        migrations.DeleteModel(
            name='Province',
        ),
        migrations.DeleteModel(
            name='Stat',
        ),
        migrations.AddField(
            model_name='date',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Country'),
        ),
    ]
