# Generated by Django 3.0.3 on 2020-04-28 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0026_auto_20200426_0213'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='country',
            index=models.Index(fields=['name', 'code'], name='dashboard_c_name_cdd91a_idx'),
        ),
    ]
