# Generated by Django 3.0.3 on 2020-04-30 05:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0029_auto_20200427_1943'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='date',
            name='dashboard_d_datetim_56cdc0_idx',
        ),
        migrations.RemoveField(
            model_name='date',
            name='datetime',
        ),
        migrations.AddField(
            model_name='date',
            name='date',
            field=models.DateField(default=datetime.date(2020, 4, 30), verbose_name='date'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='country',
            name='last_updated',
            field=models.DateField(verbose_name='last_updated'),
        ),
        migrations.AddIndex(
            model_name='date',
            index=models.Index(fields=['date', 'country'], name='dashboard_d_date_21fb65_idx'),
        ),
    ]
