# Generated by Django 3.0.3 on 2020-04-30 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0029_auto_20200427_1943'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='date',
            name='dashboard_d_datetim_56cdc0_idx',
        ),
        migrations.RemoveField(
            model_name='country',
            name='last_updated',
        ),
        migrations.RemoveField(
            model_name='date',
            name='datetime',
        ),
    ]
