# Generated by Django 3.0.3 on 2020-04-30 02:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0030_auto_20200429_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='last_updated',
            field=models.DateField(default=datetime.date(2020, 4, 30), verbose_name='last_updated'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='date',
            name='date',
            field=models.DateField(default=datetime.date(2020, 4, 30), verbose_name='date'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='date',
            index=models.Index(fields=['date', 'country'], name='dashboard_d_date_21fb65_idx'),
        ),
    ]
